# set backupcopy=yes fixes trunk to not build twice on write in neovim

[build]
target = "index.html"
dist = "dist"

[tools]
tailwindcss = "4.1.10"

[[proxy]]
backend = "http://localhost:42069/api/"

[serve]
addresses = ["0.0.0.0"]
