//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod friendships;
pub mod ingredients;
pub mod recipe_ingredients;
pub mod recipes;
pub mod sea_orm_active_enums;
pub mod users;
