//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod friendships;
pub mod ingredients;
pub mod recipe_ingredients;
pub mod recipe_share;
pub mod recipes;
pub mod sea_orm_active_enums;
pub mod users;
