//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::friendships::Entity as Friendships;
pub use super::ingredients::Entity as Ingredients;
pub use super::recipe_ingredients::Entity as RecipeIngredients;
pub use super::recipes::Entity as Recipes;
pub use super::users::Entity as Users;
