services:
  redis:
    image: redis:latest
    hostname: foodie_redis
    container_name: foodie_redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ../redis.conf:/etc/redis/redis.conf
      - ../.db/foodie_redis:/data

  postgres:
    hostname: foodie_postgres
    container_name: foodie_postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ../.db/foodie_db:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "127.0.0.1:9000:9000" # S3-compatible API
      - "127.0.0.1:9001:9001" # Web console
    volumes:
      - ../.db/aws:/data
    environment:
      MINIO_ROOT_USER: $AWS_USER
      MINIO_ROOT_PASSWORD: $AWS_PASSWORD
    command: server /data --console-address ":9001"
